name: Build and Push Docker Image to Artifact Registry

on:
  push:
    branches:
      - db-sync

env:
  PROJECT_ID: weather-sync-github
  GCP_REGION: asia-northeast2
  REPOSITORY: weather-db-sync-source
  IMAGE_NAME: weather-db-sync-source-docker

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # OIDC ID 토큰을 생성하기 위해 필요

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug GitHub Context
        run: |
          echo "github.repository: ${{ github.repository }}"
          echo "github.repository_owner: ${{ github.repository_owner }}"
          echo "github.ref: ${{ github.ref }}"

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2' # 워크로드 아이덴티티 연합을 위한 GitHub 액션
        with:
          workload_identity_provider: 'projects/560684386599/locations/global/workloadIdentityPools/weather-sync-github/providers/github-actions'
          service_account: 'cloud-run@gitblog-service.iam.gserviceaccount.com'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker ${GCP_REGION}-docker.pkg.dev

      - name: Build and Tag Docker Image
        run: |
          docker build -t ${GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${{ github.sha }} .
          docker tag ${GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${{ github.sha }} ${GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:latest

      - name: Push Docker Image to Artifact Registry
        run: |
          docker push ${GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${{ github.sha }}
          docker push ${GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:latest